name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  verify-reset-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Verify AUDIT.md is empty
      run: |
        if [ -s docs/AUDIT.md ]; then
          echo "❌ AUDIT.md is not empty"
          exit 1
        else
          echo "✅ AUDIT.md is empty"
        fi
    
    - name: Verify WIP.md is empty
      run: |
        if [ -s docs/WIP.md ]; then
          echo "❌ WIP.md is not empty"
          exit 1
        else
          echo "✅ WIP.md is empty"
        fi
    
    - name: Verify progress.json is minimal
      run: |
        expected='{"version":"1.0","entries":[]}'
        actual=$(cat progress.json)
        if [ "$actual" != "$expected" ]; then
          echo "❌ progress.json content mismatch"
          echo "Expected: $expected"
          echo "Actual: $actual"
          exit 1
        else
          echo "✅ progress.json is correct"
        fi

  build-and-test:
    runs-on: ubuntu-latest
    needs: verify-reset-files
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-build --logger trx --results-directory TestResults
    
    - name: Update reports after CI
      run: |
        mkdir -p reports/_latest
        echo "CI passed at $(date)" > reports/_latest/ci_status.txt
        echo "Build successful" > reports/_latest/build_status.txt