name: CI - Build, Test, DbSmoke

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build (Release)
        run: dotnet build -c Release --no-restore
        
      - name: Test (Release)
        run: dotnet test -c Release --no-build --logger "trx;LogFileName=test_results.trx" --collect:"XPlat Code Coverage"
        
      - name: Run DbSmoke (if connection string available)
        if: ${{ env.ConnectionStrings__DefaultConnection != '' }}
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DEFAULT_CONNECTION }}
        run: |
          if [ -d "tools/DbSmoke" ]; then
            echo "執行 DbSmoke 資料庫連線測試..."
            dotnet run --project tools/DbSmoke/ --configuration Release || exit 1
          else
            echo "DbSmoke 工具不存在，跳過資料庫測試"
          fi
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*.trx
            **/TestResults/*/coverage.cobertura.xml
          if-no-files-found: ignore
          
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            reports/
            docs/reports/
          if-no-files-found: ignore
          
      - name: Code Coverage Summary
        if: always()
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "**/TestResults/*/coverage.cobertura.xml"
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'